name: Pulumi Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set Pulumi Access Token (accessed from GitHub Secrets)
      - name: Set Pulumi Access Token
        run: echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV
      
      # Install Pulumi (example for installation)
      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "Pulumi version installed"
      
      # Setup AWS Credentials
      - name: Setup AWS Credentials
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_REGION="us-east-1"
          pulumi stack select dev
          pulumi config set aws:region $AWS_REGION


      # Run Pulumi
      - name: Run Pulumi
        run: pulumi up --yes
